const styles = {
  page: {
    minHeight: "100vh", background: "#f6f7fd",
    padding: 28, fontFamily: "'Nunito', sans-serif",
  },
  surface: {
    background: "#ffffff", borderRadius: 24, padding: 28,
    boxShadow: "0 8px 30px rgba(99, 102, 241, 0.08)",
    border: "1px solid #eef0ff", maxWidth: 1280, margin: "0 auto",
  },
  backButton: {
    display: "inline-flex", alignItems: "center", gap: 8,
    border: "none", background: "transparent", color: "#5b5bd6",
    fontSize: 14, fontWeight: 600, cursor: "pointer", padding: 0, marginBottom: 24,
  },
  heroGrid: {
    display: "grid", gridTemplateColumns: "220px minmax(0, 1fr)",
    gap: 28, alignItems: "start",
  },
  coverColumn: { width: "100%" },
  coverImage: {
    width: "100%", aspectRatio: "3 / 4.2", objectFit: "cover",
    borderRadius: 16, boxShadow: "0 10px 25px rgba(15, 23, 42, 0.14)", display: "block",
  },
  coverFallback: {
    width: "100%", aspectRatio: "3 / 4.2", borderRadius: 16,
    background: "#eef2ff", color: "#6366f1", display: "flex",
    alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 18,
  },
  infoColumn: { minWidth: 0 },
  titleRow: {
    display: "flex", justifyContent: "space-between",
    alignItems: "flex-start", gap: 16, marginBottom: 18,
  },
  title: { margin: 0, fontSize: 40, lineHeight: 1.08, color: "#111827", fontWeight: 800 },
  author: { margin: "8px 0 0", fontSize: 18, color: "#4b5563" },
  statusPill: { flexShrink: 0, padding: "8px 14px", borderRadius: 999, fontSize: 13, fontWeight: 700 },
  ownerCard: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    gap: 16, padding: 16, borderRadius: 16, border: "1px solid #eceef8",
    background: "#fbfbff", marginBottom: 18,
  },
  ownerInfo: { display: "flex", alignItems: "center", gap: 12, minWidth: 0 },
  ownerAvatar: {
    width: 42, height: 42, borderRadius: "50%",
    background: "linear-gradient(135deg, #5b5bd6, #8b5cf6)",
    color: "#fff", display: "flex", alignItems: "center",
    justifyContent: "center", fontWeight: 800, fontSize: 14, flexShrink: 0,
  },
  ownerName: { margin: 0, fontWeight: 700, fontSize: 15, color: "#111827" },
  ownerMeta: { margin: "4px 0 0", fontSize: 13, color: "#6b7280" },
  secondaryButton: {
    border: "1px solid #d9ddf4", background: "#fff", color: "#4f46e5",
    borderRadius: 12, padding: "10px 16px", fontSize: 14, fontWeight: 700,
    cursor: "pointer", whiteSpace: "nowrap",
  },
  metaGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 12, marginBottom: 18 },
  infoCard: { border: "1px solid #eceef8", borderRadius: 14, padding: "14px 16px", background: "#fff", minHeight: 84 },
  infoLabel: { margin: 0, fontSize: 12, fontWeight: 700, color: "#9ca3af", textTransform: "uppercase", letterSpacing: 0.4 },
  infoValue: { margin: "8px 0 0", fontSize: 15, color: "#111827", lineHeight: 1.4, fontWeight: 600 },
  actionRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  primaryButton: {
    border: "none", background: "linear-gradient(135deg, #4f46e5, #6d5ef4)",
    color: "#fff", borderRadius: 14, padding: "14px 24px", fontSize: 15,
    fontWeight: 800, cursor: "pointer", boxShadow: "0 10px 22px rgba(79, 70, 229, 0.24)",
  },
  primaryButtonDisabled: { opacity: 0.55, boxShadow: "none", cursor: "not-allowed" },
  readingListButton: {
    display: "inline-flex", alignItems: "center", gap: 10,
    border: "1px solid #e5e7eb", background: "#fff", color: "#111827",
    borderRadius: 14, padding: "14px 18px", fontSize: 15, fontWeight: 700, cursor: "pointer",
  },
  reactionRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginTop: 16 },
  reactionButton: {
    display: "inline-flex", alignItems: "center", gap: 8,
    border: "1px solid #e5e7eb", background: "#fff", color: "#111827",
    borderRadius: 999, padding: "10px 14px", fontSize: 14, fontWeight: 700, cursor: "pointer",
  },
  reactionButtonActive: { background: "#fef2f2", borderColor: "#fecaca", color: "#dc2626" },
  reactionButtonDanger: { background: "#fff7ed", borderColor: "#fdba74", color: "#c2410c" },
  helperText: { fontSize: 13, color: "#6b7280" },
  contentGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 300px", gap: 24, marginTop: 32 },
  tabs: { display: "flex", gap: 20, borderBottom: "1px solid #eceef8", marginBottom: 18 },
  tabButton: {
    border: "none", background: "transparent", color: "#6b7280",
    fontSize: 15, fontWeight: 700, padding: "0 2px 12px",
    cursor: "pointer", borderBottom: "2px solid transparent",
  },
  tabButtonActive: { color: "#4f46e5", borderBottomColor: "#4f46e5" },
  tabPanel: { background: "#fff", minHeight: 220 },
  description: { margin: 0, fontSize: 16, lineHeight: 1.85, color: "#374151", maxWidth: 720 },
  commentComposer: { border: "1px solid #eceef8", borderRadius: 18, padding: 16, background: "#fbfbff", marginBottom: 16 },
  commentTextarea: {
    width: "100%", border: "1px solid #dbe1ff", borderRadius: 14,
    padding: "12px 14px", fontSize: 14, lineHeight: 1.6, fontFamily: "inherit",
    color: "#111827", outline: "none", resize: "vertical", boxSizing: "border-box", background: "#fff",
  },
  commentComposerFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginTop: 12 },
  commentState: { border: "1px dashed #d9ddf4", borderRadius: 16, padding: 24, color: "#6b7280", fontSize: 14, background: "#fbfbff" },
  commentsList: { display: "grid", gap: 14 },
  commentCard: { border: "1px solid #eceef8", borderRadius: 18, padding: 16, background: "#fff" },
  replyCard: { border: "1px solid #eceef8", borderRadius: 16, padding: 14, background: "#f8faff" },
  replyList: { display: "grid", gap: 10, marginTop: 14, marginLeft: 18 },
  commentHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  commentAuthor: { margin: 0, fontSize: 14, fontWeight: 700, color: "#111827" },
  commentTime: { margin: "4px 0 0", fontSize: 12, color: "#9ca3af" },
  commentBody: { margin: "12px 0 0", fontSize: 14, color: "#374151", lineHeight: 1.8 },
  commentActions: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  linkButton: { border: "none", background: "transparent", color: "#4f46e5", fontSize: 13, fontWeight: 700, cursor: "pointer", padding: 0 },
  linkButtonDanger: { border: "none", background: "transparent", color: "#dc2626", fontSize: 13, fontWeight: 700, cursor: "pointer", padding: 0 },
  replyComposer: { marginTop: 14, paddingTop: 14, borderTop: "1px solid #eef2ff" },
  inlineActionRow: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 10 },
  relatedPanel: { border: "1px solid #eceef8", borderRadius: 18, padding: 18, background: "#fbfbff", alignSelf: "start" },
  relatedTitle: { margin: "0 0 16px", fontSize: 18, fontWeight: 800, color: "#111827" },
  relatedEmpty: { margin: 0, fontSize: 14, color: "#6b7280" },
  relatedItem: { display: "grid", gridTemplateColumns: "74px minmax(0, 1fr)", gap: 12, width: "100%", padding: 0, border: "none", background: "transparent", textAlign: "left", cursor: "pointer", marginBottom: 14 },
  relatedImage: { width: 74, height: 104, objectFit: "cover", borderRadius: 12, display: "block" },
  relatedImageFallback: { width: 74, height: 104, borderRadius: 12, background: "#eef2ff", color: "#6366f1", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 13 },
  relatedMeta: { minWidth: 0 },
  relatedBookTitle: { margin: 0, fontSize: 15, fontWeight: 800, color: "#111827", lineHeight: 1.4 },
  relatedBookAuthor: { margin: "6px 0 0", fontSize: 13, color: "#6b7280" },
  relatedBookPrice: { margin: "10px 0 0", fontSize: 14, color: "#4f46e5", fontWeight: 700 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(17, 24, 39, 0.38)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 2000 },
  modalCard: { width: "100%", maxWidth: 560, background: "#fff", borderRadius: 22, padding: 22, boxShadow: "0 24px 60px rgba(15, 23, 42, 0.22)" },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 18 },
  modalTitle: { margin: 0, fontSize: 22, fontWeight: 800, color: "#111827" },
  closeButton: { border: "none", background: "#f3f4f6", width: 34, height: 34, borderRadius: 10, cursor: "pointer", color: "#6b7280", fontSize: 16, fontWeight: 700 },
  modalState: { border: "1px dashed #d9ddf4", borderRadius: 16, padding: 20, textAlign: "center", color: "#6b7280" },
  optionList: { display: "grid", gap: 10 },
  optionCard: { border: "1px solid #eceef8", borderRadius: 16, padding: "14px 16px", background: "#fff", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, cursor: "pointer", textAlign: "left" },
  optionCardActive: { borderColor: "#818cf8", background: "#eef2ff" },
  optionTitle: { margin: 0, fontSize: 15, fontWeight: 800, color: "#111827" },
  optionMeta: { margin: "4px 0 0", fontSize: 13, color: "#6b7280" },
  optionSelect: { color: "#4f46e5", fontSize: 14, fontWeight: 800, whiteSpace: "nowrap" },
  modalFooter: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 18, flexWrap: "wrap" },
  statePanel: { background: "#fff", borderRadius: 24, padding: 28, minHeight: 260, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 16, boxShadow: "0 8px 30px rgba(99, 102, 241, 0.08)", border: "1px solid #eef0ff" },
  stateText: { margin: 0, fontSize: 16, fontWeight: 700 },
  toast: { position: "fixed", top: 18, right: 22, color: "#fff", padding: "12px 16px", borderRadius: 14, fontSize: 14, fontWeight: 700, zIndex: 2500, boxShadow: "0 14px 30px rgba(15, 23, 42, 0.2)" },
};

export default styles;