namespace BookCircle.Enums
{
public enum NotificationType{
        BORROW_REQUEST=0,
BORROW_ACCEPTED=1,
        BORROW_REJECTED=2,
        COMMENT_ADDED=3,
        COMMENT_REPLIED=4,
        BOOK_LIKED=5,
BOOK_DISLIKED=6,
        BOOK_APPROVED=7,
BOOK_REJECTED=8,
        OWNER_APPROVED=9,
OWNER_REJECTED=10,
ACCOUNT_REQUEST=11,
    }
}
