export const styles = {
  wrapper:    { padding: 32, background: "#F9FAFB", minHeight: "100vh", fontFamily: "Inter, sans-serif" },
  header:     { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  h1:         { fontSize: 22, fontWeight: 600, color: "#111827", margin: 0 },
  sub:        { fontSize: 13, color: "#6B7280", marginTop: 2 },
  tabBar:     { display: "flex", gap: 4, marginBottom: 20, background: "#fff", borderRadius: 10, padding: 4, width: "fit-content", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  tab:        { padding: "7px 18px", borderRadius: 8, border: "none", background: "transparent", fontSize: 13, fontWeight: 500, color: "#6B7280", cursor: "pointer" },
  tabActive:  { background: "#4F46E5", color: "#fff" },
  card:       { background: "#fff", borderRadius: 16, padding: 16, boxShadow: "0 1px 3px rgba(0,0,0,0.08)", overflowX: "auto" },
  table:      { width: "100%", borderCollapse: "collapse" },
  th:         { textAlign: "left", fontSize: 13, fontWeight: 600, color: "#6B7280", padding: "8px 12px", borderBottom: "1px solid #eee"},
  td:         { padding: 12, verticalAlign: "middle", fontSize: 14, color: "#111827", wordBreak: "break-word" },
  row:        { borderBottom: "1px solid #f5f5f5" },
  title:      { margin: 0, fontWeight: 600, fontSize: 14 },
  meta:       { margin: "3px 0 0", fontSize: 12, color: "#6B7280" },
  price:      { fontWeight: 600, color: "#4F46E5", fontSize: 14 },
  img:        { width: 80, height: 56, borderRadius: 8, objectFit: "cover" },
  empty:      { textAlign: "center", padding: 20, color: "#9CA3AF" },
  actions:    { display: "flex", gap: 8, flexWrap: "wrap"   },
  btnPrimary: { background: "#4F46E5", color: "#fff", border: "none", borderRadius: 8, padding: "8px 16px", fontSize: 13, fontWeight: 500, cursor: "pointer", whiteSpace: "nowrap" },
  btnView:    { background: "#F3F4F6", color: "#374151", border: "none", borderRadius: 6, padding: "5px 10px", cursor: "pointer", fontSize: 13 },
  btnDelete:  { background: "#FFEDD5", color: "#C2410C", border: "none", borderRadius: 6, padding: "5px 10px", cursor: "pointer", fontSize: 13 ,    width: "90px"},
  select:     { border: "1px solid #E5E7EB", borderRadius: 6, padding: "5px 10px", fontSize: 13, color: "#111827" },
  overlay:    { position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200 },
  modal:      { background: "#fff", borderRadius: 16, padding: 24, width: 380, maxWidth: "95%" },
  modalTitle: { fontSize: 16, fontWeight: 600, marginBottom: 16 },
  label:      { fontSize: 13, color: "#6B7280", display: "block", marginBottom: 4 },
  input:      { width: "100%", border: "1px solid #E5E7EB", borderRadius: 8, padding: "8px 12px", fontSize: 14, marginBottom: 14, outline: "none", boxSizing: "border-box" },
  modalActions:       { display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 12 },
  bookRow:            { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0", borderBottom: "1px solid #eee" },
  searchRow:          { display: "flex", flexDirection: "column", gap: 10, marginBottom: 10 },
  pillGroup:          { display: "flex", gap: 6 },
  pill:               { padding: "5px 14px", borderRadius: 20, border: "1.5px solid #E5E7EB", background: "#F9FAFB", fontSize: 12, fontWeight: 500, color: "#6B7280", cursor: "pointer" },
  pillActive:         { background: "#EEF2FF", borderColor: "#4F46E5", color: "#4F46E5" },
  searchInputWrapper: { display: "flex", alignItems: "center", border: "1.5px solid #E5E7EB", borderRadius: 10, padding: "8px 12px", gap: 8, background: "#fff" },
  searchIcon:         { fontSize: 14 },
  searchInput:        { flex: 1, border: "none", outline: "none", fontSize: 14, color: "#111827", background: "transparent" },
  clearBtn:           { background: "none", border: "none", color: "#9CA3AF", cursor: "pointer", fontSize: 14, padding: 0 },
  activeBadge:        { background: "#EEF2FF", color: "#4F46E5", borderRadius: 8, padding: "5px 10px", fontSize: 12, marginBottom: 8, display: "flex", alignItems: "center", gap: 2 },
  emptyState:         { textAlign: "center", padding: "24px 0" },
  errorBox:           { background: "#FEF2F2", color: "#DC2626", borderRadius: 8, padding: "8px 12px", fontSize: 13, marginBottom: 8 },
};