const styles = {
  page: {
    minHeight: "100vh",
    background: "#f6f7fd",
    padding: 28,
    fontFamily: "'Nunito', sans-serif",
  },
  surface: {
    background: "#ffffff",
    borderRadius: 24,
    padding: 28,
    boxShadow: "0 8px 30px rgba(99, 102, 241, 0.08)",
    border: "1px solid #eef0ff",
    maxWidth: 1280,
    margin: "0 auto",
  },

  // ── Hero ─────────────────────────────────────────────────────
  heroCard: {
    background: "linear-gradient(135deg, #eef2ff 0%, #f5f3ff 100%)",
    borderRadius: 20,
    padding: "32px 28px",
    display: "flex",
    alignItems: "center",
    gap: 24,
    marginBottom: 32,
    border: "1px solid #e0e7ff",
    flexWrap: "wrap",
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #5b5bd6, #8b5cf6)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 32,
    flexShrink: 0,
    boxShadow: "0 8px 20px rgba(91, 91, 214, 0.30)",
  },
  heroInfo: { flex: 1, minWidth: 0 },
  heroName: {
    margin: 0,
    fontSize: 28,
    fontWeight: 800,
    color: "#111827",
    lineHeight: 1.15,
  },
  heroRole: {
    margin: "6px 0 0",
    fontSize: 14,
    color: "#6b7280",
    fontWeight: 600,
    textTransform: "capitalize",
  },
  heroStats: {
    display: "flex",
    gap: 16,
    marginTop: 16,
    flexWrap: "wrap",
  },
  statChip: {
    background: "#fff",
    border: "1px solid #e0e7ff",
    borderRadius: 12,
    padding: "8px 16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: 80,
    boxShadow: "0 2px 8px rgba(99,102,241,0.07)",
  },
  statNumber: {
    fontSize: 22,
    fontWeight: 800,
    color: "#4f46e5",
    lineHeight: 1,
  },
  statLabel: {
    fontSize: 11,
    color: "#9ca3af",
    fontWeight: 600,
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  // ── Section ───────────────────────────────────────────────────
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
    color: "#111827",
  },
  sectionCount: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: 600,
  },

  // ── Book grid ─────────────────────────────────────────────────
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 20,
  },

  // ── Book card ─────────────────────────────────────────────────
  card: {
    background: "#fff",
    borderRadius: 18,
    overflow: "hidden",
    boxShadow: "0 2px 12px rgba(99,102,241,0.07)",
    border: "1px solid #eef0ff",
    transition: "transform 0.2s, box-shadow 0.2s",
    cursor: "pointer",
  },
  coverWrap: {
    position: "relative",
    height: 200,
    overflow: "hidden",
    background: "#eef2ff",
  },
  coverImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  coverFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 40,
    color: "#a5b4fc",
  },
  statusPill: {
    position: "absolute",
    top: 10,
    left: 10,
    padding: "3px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
  },
  cardBody: { padding: "14px 16px 16px" },
  cardTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 800,
    color: "#111827",
    lineHeight: 1.35,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  cardMeta: {
    margin: "5px 0 0",
    fontSize: 12,
    color: "#9ca3af",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  cardPrice: {
    margin: "10px 0 0",
    fontSize: 15,
    fontWeight: 800,
    color: "#4f46e5",
  },
  cardDuration: {
    fontWeight: 400,
    color: "#9ca3af",
    fontSize: 12,
    marginLeft: 4,
  },
  detailsBtn: {
    marginTop: 12,
    width: "100%",
    padding: "9px 0",
    border: "none",
    borderRadius: 12,
    background: "linear-gradient(135deg, #4f46e5, #6d5ef4)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(79,70,229,0.22)",
  },

  // ── Empty state ───────────────────────────────────────────────
  emptyWrap: {
    gridColumn: "1 / -1",
    textAlign: "center",
    padding: "56px 0",
    color: "#9ca3af",
  },
  emptyIcon: { fontSize: 48, marginBottom: 12 },
  emptyText: { margin: 0, fontSize: 15, fontWeight: 600 },
  emptySubText: { margin: "6px 0 0", fontSize: 13 },

  // ── States ────────────────────────────────────────────────────
  stateWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "60vh",
    gap: 12,
    color: "#6b7280",
    fontSize: 15,
    fontWeight: 600,
  },
  errorText: { color: "#dc2626" },

  // ── Toast ─────────────────────────────────────────────────────
  toast: {
    position: "fixed",
    top: 18, right: 22,
    color: "#fff",
    padding: "12px 16px",
    borderRadius: 14,
    fontSize: 14,
    fontWeight: 700,
    zIndex: 2500,
    boxShadow: "0 14px 30px rgba(15,23,42,0.2)",
  },
};

export default styles;